ALTER TABLE USER_PROFILE ADD MINUTES_IN_CONVERSATION INTEGER;
ALTER TABLE USER_PROFILE ADD MEDIAN_MESSAGES_PER_CONVERSATION INTEGER;
ALTER TABLE USER_PROFILE ADD CONVERSATION_COUNT_STARTED_BY_PROMPTS INTEGER;
ALTER TABLE USER_PROFILE ADD BEST_PROMPT TEXT;
