ALTER TABLE CONVERSATION_SUMMARY ADD HEADLINE TEXT;
ALTER TABLE CONVERSATION_SUMMARY ADD IS_FEATURED INTEGER;
ALTER TABLE CONVERSATION ADD HEADLINE TEXT;
ALTER TABLE CONVERSATION ADD IS_FEATURED INTEGER;
ALTER TABLE USER_PROFILE ADD SECONDS_IN_CONVERSATION INTEGER;
