ALTER TABLE CONVERSATION_SUMMARY ADD DESCRIPTION TEXT;
ALTER TABLE CONVERSATION_SUMMARY ADD LAST_MESSAGE_SENT_BY_ME TEXT;
ALTER TABLE CONVERSATION_SUMMARY ADD PICTURE_URL TEXT;
ALTER TABLE CONVERSATION ADD DESCRIPTION TEXT;
ALTER TABLE CONVERSATION ADD LAST_MESSAGE_SENT_BY_ME TEXT;
ALTER TABLE CONVERSATION ADD PICTURE_URL TEXT;
ALTER TABLE CONVERSATION ADD CHILD_CONVERSATION_COUNT INTEGER;
